trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: npm ci
  displayName: Install dependencies

- script: npx playwright install --with-deps
  displayName: Install browsers

- script: npx playwright test --grep @api
  displayName: Run tests

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/results.xml'
    failTaskOnFailedTests: true

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    pathToPublish: 'playwright-report'
    artifactName: 'PlaywrightReport'

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    pathToPublish: 'test-results'
    artifactName: 'TestResultsFiles'